#!/usr/bin/env bash

get_brightness() {
	brightness=$(brightnessctl g)
    # percentage=$(($brightness / 255))
	echo "$brightness"
}

notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Brightness : $(get_brightness)/255"
}

inc_brightness() {
    brightnessctl s +10% && notify_user
}

dec_brightness() {
    brightnessctl s 10%- && notify_user
}

if [[ "$1" == "--inc" ]]; then
	inc_brightness
elif [[ "$1" == "--dec" ]]; then
	dec_brightness
else
	get_brightness
fi
