#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = hypridle
exec-once = hyprpaper
exec-once = mako --output DP-3
exec-once = tmux setenv -g HYPRLAND_INSTANCE_SIGNATURE "$HYPRLAND_INSTANCE_SIGNATURE"
exec-once = hyprctl setcursor WhiteSur-cursors 20
exec-once = nwg-dock-hyprland -i 40 -p bottom -a center -mb 8 -l overlay

# GTK/GNOME settings
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "WhiteSur-Dark"
exec-once = gsettings set org.gnome.desktop.interface icon-theme "WhiteSur-dark"
exec-once = gsettings set org.gnome.desktop.interface cursor-theme "WhiteSur-cursors"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = gsettings set org.gnome.desktop.interface font-name "Inter 10"
