##############################
### WINDOWS AND WORKSPACES ###
##############################

# https://wiki.hyprland.org/Configuring/Workspace-Rules/

workspace = 1,  monitor:DP-3, default:true
workspace = 2,  monitor:DP-3
workspace = 3,  monitor:DP-3
workspace = 4,  monitor:DP-3
workspace = 5,  monitor:DP-3
workspace = 6,  monitor:HDMI-A-1, default:true
workspace = 7,  monitor:HDMI-A-1
workspace = 8,  monitor:HDMI-A-1
workspace = 9,  monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

# https://wiki.hyprland.org/Configuring/Window-Rules/


windowrule = suppress_event maximize, match:class .* # You'll probably like this.

# steam fixes
windowrule = stay_focused on, match:title ^$, match:class ^(steam)$
windowrule = min_size 1 1, match:title ^$, match:class ^(steam)$
