[package]
name = "couleur"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
toml_edit = { version = "0.22.22", features = ["serde"] }
